### ISSUE TITLE
Enable deployment of the Elasticsearch curator

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1103]
After we set the logging of the OpenStack services to debug, a lot of logs collect in Elasticsearch.

In the testbed it is sufficient if we have the last hour of logs. The curator must be activated accordingly.

**Comment by berendt** [comment]
By default, the curator runs only once a day and you can go down to 1 day at most. For hourly deletion we would have to extend the curator.

```
elasticsearch_curator_cron_schedule: "0 {{ elasticsearch_curator_instance_id }} * * *"
elasticsearch_curator_soft_retention_period_days: 30
elasticsearch_curator_hard_retention_period_days: 60
```

**Comment by berendt** [comment]
It is possible to use a custom `elasticsearch-curator-actions.yml` file. This way it is not a problem to delete every hour or so.

**Comment by berendt** [comment]
```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indicies
    options:
      ignore_empty_list: True
      continue_if_exception: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: "{{ elasticsearch_curator_index_pattern }}"
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: "{{ elasticsearch_curator_hard_retention_period_days }}"
  2:
    action: close
    description: >-
      Closes indices
    options:
      ignore_empty_list: True
      continue_if_exception: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: "{{ elasticsearch_curator_index_pattern }}"
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: "{{ elasticsearch_curator_soft_retention_period_days }}"
```
