### ISSUE TITLE
Ansible-lint: Risky filepermissions for downloaded files

### ISSUE THREAD

**Issue by ra-rau** [osism/testbed#1179]
Ansible-lint throws a warning like this:
```
risky-file-permissions: File permissions unset or incorrect.
environments/openstack/playbook-bootstrap-refstack.yml:120 Task/Handler: Download image
```

Ansible-lint suggests to set file permissions with parameter `mode` in this codeblock:
```
    - name: Download image
      ansible.builtin.get_url:
        url: https://github.com/cirros-dev/cirros/releases/download/0.5.2/cirros-0.5.2-x86_64-disk.img
        dest: /tmp/image.img
```
