### ISSUE TITLE
Software version requirements for ansible+terraform  

### ISSUE THREAD

**Issue by frosty-geek** [osism/testbed#1454]
I've just tried to create a testbed using the Ubuntu 22.04 ansible version which failed due to it being Ansible 2.x.

[Requirements](https://docs.osism.tech/testbed/requirements.html#software) states that Ansible 6.x + Terraform 1.2.x is required, but it's not that obvious that the latest Ubuntu LTS version is not sufficient. [Quickstart](https://docs.osism.tech/testbed/quickstart.html) also does not stress this enough IMVHO.

I suggest that "make prepare" should either make sure the ansible+terraform version are installed in the minimal required version or throw an error to indicate there are no usable Versions available.

Comments?

**Comment by berendt** [comment]
A check in prepare makes sense.

Checking which ansible or terraform version is supplied out of the box for all possible distributions makes no sense in IMO.

On Ubuntu, when you install Ansible via APT, you actually want to use the PPA (https://launchpad.net/~ansible/+archive/ubuntu/ansible).

**Comment by fkr** [comment]
When I dove into this around christmas, I once again (even though I previously ran through it just fine) had a hard time.
However I do think that stating the versions of the software required should be enough (now referring to the quickstart guide), since if it is elaborated on how to install that software on each and every operating system it becomes not only impossible to maintain but also hard to consume.
The sanity check in `make prepare` wether the right versions are present makes sense imho.

**Comment by frosty-geek** [comment]
not being an ansible expert, wouldn't something like

```yaml
---
- hosts: localhost
  tasks:

    - name: Fail if ansible version is lower than 6.0.0
    ansible.builtin.fail:
        msg: "Ansible version is  {{ ansible_version.full }}, see required software"
      when: ansible_version.full < "6.0.0"
```

be enough for `make prepare`
