### ISSUE TITLE
Hardcoded Repository Path

### ISSUE THREAD

**Issue by Richie1710** [osism/testbed#2356]
Hello,
Currently, the repository path is hardcoded, which may cause issues when running the playbook from a forked repository. Could you please make the repository path configurable to ensure it works seamlessly across different forks?

Here is the code snippet in question:
```
    - name: Copy testbed repo
      become: true
      become_user: dragon
      ansible.posix.synchronize:
        src: "{{ repo_path }}/osism/testbed/"
        delete: true
        dest: /opt/configuration
```

You can find this in the following file: 
https://github.com/osism/testbed/blob/main/ansible/manager-part-1.yml#L45
