### ISSUE TITLE
mtu greater than device maximum

### ISSUE THREAD

**Issue by frosty-geek** [osism/testbed#618]
if the maxmtu of an interface is smaller than the default 1450 mtu the default route fails as the interface fails to come up

```
root@testbed-manager:/etc/network/interfaces.d# ip addr flush dev ens7
root@testbed-manager:/etc/network/interfaces.d# ip -d link show dev ens7
6: ens7: <BROADCAST,MULTICAST> mtu 1442 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:c0:36:0f brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 1442 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 

root@testbed-manager:/etc/network/interfaces.d# cat device-ens7 
# Ansible managed

auto ens7

iface ens7 inet static
  address 192.168.64.5
  netmask 255.255.240.0
  mtu 1450

root@testbed-manager:/etc/network/interfaces.d# ifup ens7
Error: mtu greater than device maximum.
ifup: failed to bring up ens7
```

ens7 is only an example, all interfaces fail to come up correctly thus there is no default route and the manager is inaccessible from the outside world.

```
root@testbed-manager:/etc/network/interfaces.d# cat /etc/netplan/50-cloud-init.yaml.unused 
[...]
        ens7:
            addresses:
            - 192.168.64.5/20
            match:
                macaddress: fa:16:3e:c0:36:0f
            mtu: 1442
            nameservers:
                addresses:
                - 8.8.8.8
                - 9.9.9.9
                search: []
            routes:
            -   to: 0.0.0.0/0
                via: 192.168.64.1
            set-name: ens7
```
